deployment:
  image:
    repository: nexus.bmwgroup.net/grafana/k6-operator
    tag: latest

  replicas: 1

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 150Mi

ingress:
  address: echo-test.apps.4wm-development.azure.cloud.bmw
