deployment:
  image:
    repository: public.ecr.aws/v7n2v9r3/4wm-echo-server
    tag: latest

  replicas: 1

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 150Mi

ingress:
  address:  echo-server-test.apps.4wm-development.azure.cloud.bmw
